[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pysym2md"
dynamic = ["version"]
description = "Generate manifest of public symbols win python projects w/docstrings"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache-2.0"}
authors = [{name = "Hamel Husain", email = "hamel.husain@gmail.com"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['fastcore>=1.14.6', 'astroid']

[project.urls]
Repository = "https://github.com/AnswerDotAI/pysym2md"
Documentation = "https://AnswerDotAI.github.io/pysym2md"

[project.entry-points.nbdev]
pysym2md = "pysym2md._modidx:d"


[project.scripts]
pysym2md = "pysym2md.core:pysym2md"

[tool.setuptools.dynamic]
version = {attr = "pysym2md.__version__"}

[tool.setuptools.packages.find]
include = ["pysym2md"]

[tool.nbdev]
allowed_metadata_keys = ['solveit']
allowed_cell_metadata_keys = ['solveit_ai']
custom_sidebar = false

[tool.chkstyle]
skip_paths = ["_modidx.py"]
