# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pysymbol-llm',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/pysymbol-llm',
                'lib_path': 'pysymbol_llm'},
  'syms': {'pysymbol_llm.core': {'pysymbol_llm.core.foo': ('core.html#foo', 'pysymbol_llm/core.py')}}}
