# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pysymbol-llm',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/pysymbol-llm',
                'lib_path': 'pysymbol_llm'},
  'syms': { 'pysymbol_llm.core': { 'pysymbol_llm.core._process_method': ('core.html#_process_method', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.format_symbol': ('core.html#format_symbol', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.generate_markdown': ('core.html#generate_markdown', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.get_decorators': ('core.html#get_decorators', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.get_params': ('core.html#get_params', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.get_public_symbols': ('core.html#get_public_symbols', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.is_public_symbol': ('core.html#is_public_symbol', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.is_valid_method': ('core.html#is_valid_method', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.log_error': ('core.html#log_error', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.process_class': ('core.html#process_class', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.process_function': ('core.html#process_function', 'pysymbol_llm/core.py'),
                                   'pysymbol_llm.core.pysym2md': ('core.html#pysym2md', 'pysymbol_llm/core.py')}}}
